<?php

/**
 * @file
 * Contains simple_social_icons.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @inheritdoc
 */
function simple_social_icons_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the simple_social_share_block module.
    case 'help.page.simple_social_share_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple social Icons') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_attachments().
 *
 * @inheritdoc
 */
function simple_social_icons_page_attachments(array &$attachments) {
  // $attachments['#attached']['library'][] = 'simple_social_icons/simple_social_icons';
}