<?php

/**
 * @file
 * Contains behaviour_builder.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function behaviour_builder_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the behaviour_builder module.
    case 'help.page.behaviour_builder':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('For generating code for behaviour testing in drupal using behat.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function behaviour_builder_theme($existing, $type, $theme, $path) {
  return array(
    'home' => array(
      'variables' => array('test_var' => NULL),
    ),
  );
}

/**
 * Implements hook_user_login().
 */
function behaviour_builder_user_login($account) {
  if($account->id() > 0) {
    $saved_data = db_select('behave_builds', 'b')
    ->fields('b', array('data', 'build_no'))
    ->condition('b.uid', $account->id())
    ->execute()->fetch(\PDO::FETCH_OBJ);
    if(isset($saved_data) && !empty($saved_data)) { 
      $_SESSION['behave_drupal']['auto_save'] = json_decode($saved_data->data, TRUE);
    }       
  }  
}

/**
 * Implements hook_user_logout().
 */
function behaviour_builder_user_logout($account) {
  /*
  \Drupal::service('user.data')->set('contact', $account->id(), 'enabled');
  db_insert('logouts')
    ->fields(array(
      'uid' => $account->id(),
      'time' => time(),
    ))
    ->execute();
  */
}