avatars.settings:
  type: config_object
  label: 'Avatar Kit settings'
  mapping:
    refresh_interval:
      type: mapping
      mapping:
        dynamic:
          type: integer
          label: 'How long should dynamic avatars be cached before allowing refresh.'
        static:
          type: integer
          label: 'How long should non-preferred static avatars be cached. Leave empty to never delete. Preferred static avatars never expire.'

avatars.generator.*:
  type: config_entity
  label: 'Avatar Generator'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    plugin:
      type: string
      label: 'Plugin'
    provider:
      type: string
      label: 'Provider'
    settings:
      type: avatar_generator.settings.[%parent.plugin]

avatar_generator.settings.*:
  type: avatar_generator_settings

field.widget.settings.avatars_generator_preview:
  type: mapping
  label: 'Avatar generator preview settings'
  mapping:
    preview_image_style:
      type: string
      label: 'Preview image style'
