avatar_generator.settings.robohash:
  type: avatar_generator_settings
  label: 'Robohash'
  mapping:
    type:
      type: string
      label: 'Type'
    background:
      type: string
      label: 'Background'